# This workflow only runs when manually triggered, and calls a reusable workflow to run the CLI on all repos in OpenNeuroDatasets-JSONLD.
name: Run CLI on all repos

on:
  workflow_dispatch:
    inputs:
      clear_sha:
        description: "Whether to clear the sha.txt file (default: false)"
        required: false
        default: "false"

jobs:
    get-repos:
      name: Get repos
      runs-on: ubuntu-latest
      outputs:
        dataset_list: ${{ steps.get-repos.outputs.repos }}

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Clear existing sha.txt
          if: ${{ github.event.inputs.clear_sha == 'true' }}
          run: |
            echo "Clearing existing sha.txt file."
            > code/sha.txt

        # This step gets a list of all repos in OpenNeuroDatasets-JSONLD, and fetches each repo's latest SHA.
        # If the repo contains the required files for the bagel CLI, the repo ID and its latest SHA are written to a job output variable "repos"
        # which forms the list the CLI will run on.
        # Otherwise, the repo SHA is written directly to sha.txt.
        - id: get-repos
          name: Get repos
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          working-directory: code
          # NOTE: When a repo doesn't exist, the curl command complains confusingly: jq: error (at <stdin>:4): Cannot index object with number
          run: |
            ./sha_scraper.sh --all-repos 2>&1 | tee -a LOG.txt

            # The following syntax ensures that "repos" is a multiline string, where each line represents one repo
            # See: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
            echo 'repos<<EOF' >> "$GITHUB_OUTPUT"
            for line in $(cat repos_for_cli.txt); do
              echo $line >> "$GITHUB_OUTPUT"
            done
            echo 'EOF' >> "$GITHUB_OUTPUT"

        # Upload the log from the sha scraper process for debugging purposes
        - name: Upload log file as artifact
          uses: actions/upload-artifact@v4
          with:
            name: log-file
            path: code/LOG.txt

        - name: Commit and push updated sha.txt file
          # NOTE: git push only has access to whatever branch is currently checked out
          run: |
            if ! git diff --quiet code/sha.txt; then
              git config user.name "GitHub Actions Bot"
              git config user.email "<>"
              git add code/sha.txt
              git commit -m "[bot] Update record of repo SHAs"
              git push origin main
            fi

    call-run-cli-on-repo-list:
      needs: get-repos
      uses: OpenNeuroDatasets-JSONLD/.github/.github/workflows/run_cli_on_repo_list.yml@main
      with:
        dataset_list: ${{ needs.get-repos.outputs.dataset_list }}
        clear_old_jsonlds: true
      secrets: inherit