name: Run CLI on repo update

on:
  schedule:
    - cron: '31 12,0 * * *'
  workflow_dispatch:
  push:
    branches:
      - thursday-adventures

jobs:
    joblist:
        name: Get updated JSONLD files
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up Python 3.10
          uses: actions/setup-python@v5
          with:
            python-version: "3.10"
        
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r code/requirements.txt

        - name: Detect changes and run CLI
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          working-directory: code
          run: |
            ./sha_scraper.sh 2>&1 | tee -a LOG.txt
        
        - name: Upload JSONLD files as artifacts
          uses: actions/upload-artifact@v4
          with:
            name: jsonld-files
            path: code/data/jsonld

        - name: Upload log file as artifact
          uses: actions/upload-artifact@v4
          with:
            name: log-file
            path: code/LOG.txt

        - name: Upload sha.txt file as artifact
          uses: actions/upload-artifact@v4
          with:
            name: sha-file
            path: code/sha.txt