# This workflow calls a reusable workflow to run the CLI on all repos in OpenNeuroDatasets-JSONLD.
name: Run CLI on all repos

on:
  workflow_dispatch:
  push:
    branches:
      - add-cli-runner-wf

jobs:
    get-repos:
      name: Get repos
      runs-on: ubuntu-latest
      outputs:
        dataset_list: ${{ steps.get-repos.outputs.repos }}

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        # This step gets a list of all repos in OpenNeuroDatasets-JSONLD, and fetches each repo's latest SHA
        # Each repo ID and its corresponding SHA are written to a job output variable "repos"
        #
        # We use syntax here to ensure that "repos" is a multiline string, where each line represents one repo
        # See: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
        - id: get-repos
          name: Get repos
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          working-directory: code
          # TODO: Replace hardcoded repos with commmand to fetch full list
          # NOTE: When a repo doesn't exist, the curl command complains confusingly: jq: error (at <stdin>:4): Cannot index object with number
          run: |
            OWNER="OpenNeuroDatasets-JSONLD"
            reposON_LD="ds000001 ds000002 ds000003 ds000005 ds000006"

            echo 'repos<<EOF' >> "$GITHUB_OUTPUT"
            for repo in $reposON_LD; do
              sha=$(curl -L \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${GH_TOKEN}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/${OWNER}/${repo}/commits | jq .[0].sha)
              echo $repo,$sha >> "$GITHUB_OUTPUT"
            done
            echo 'EOF' >> "$GITHUB_OUTPUT"

    call-run-cli-on-repo-list:
      needs: get-repos
      # if: ${{ needs.get-updated-files.outputs.dataset_list != '' }}
      # TODO: Replace with full workflow reference: OpenNeuroDatasets-JSONLD/.github/workflows/run_cli_on_repo_list.yml@main
      uses: ./.github/workflows/run_cli_on_repo_list.yml
      with:
        dataset-list: ${{ needs.get-repos.outputs.dataset_list }}
      secrets: inherit