name: Run CLI on changed repos

on:
  schedule:
    - cron: '31 12,0 * * *'
  workflow_dispatch:
  push:
    branches:
      - add-cli-runner-wf

jobs:
    get-updated-files:
      name: Get updated JSONLD files
      runs-on: ubuntu-latest
      outputs:
        dataset_list: ${{ steps.detect-changed-repos.outputs.changed_repos }}

      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            ref: 'add-cli-runner-wf'
            token: ${{ secrets.ON_WF_PAT }}

        - id: detect-changed-repos
          name: Detect changed repos
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          working-directory: code
          run: |
            ./sha_scraper.sh 2>&1 | tee -a LOG.txt
            echo "changed_repos=$(cat changed_repos.txt)" >> "$GITHUB_OUTPUT"
        
        # TODO: Push LOG.txt to some repo
        - name: Upload log file as artifact
          uses: actions/upload-artifact@v4
          with:
            name: log-file
            path: code/LOG.txt

        # NOTE: sha.txt needs to be updated twice. Can't share artifacts across wfs?
        # - name: Upload sha.txt file as artifact
        #   uses: actions/upload-artifact@v4
        #   with:
        #     name: sha-file
        #     path: code/sha.txt
        - name: Commit and push updated sha.txt file
          run: |
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"
            git add code/sha.txt
            git commit -m "[bot] Update record of repo SHAs"
            git push origin add-cli-runner-wf

    call-cli-runner:
      needs: get-updated-files
      uses: OpenNeuroDatasets-JSONLD/.github/workflows/run_cli_on_repo_list.yml@add-cli-runner-wf
      with:
        dataset-list: ${{ needs.get-updated-files.outputs.dataset_list }}